name: Backend-CI

on:
  push:
    branches: [master]
    paths:
      - "**"
  pull_request:
    branches: [master]
    paths:
      - "**"

jobs:
  build-backend:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./
    strategy:
      matrix:
        os: [windows-latest]
        dotnet-version: ["3.1.101"]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build solution
        run: dotnet build
